# Generated by Django 2.2.6 on 2019-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0002_inloggen'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dag', models.TextField()),
                ('beschrijving', models.CharField(max_length=255)),
                ('starttijd', models.DateTimeField(verbose_name='starttijd')),
                ('eindtijd', models.DateTimeField(verbose_name='eindtijd')),
            ],
        ),
    ]
