# Generated by Django 2.2.6 on 2019-10-15 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soccer', '0003_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='notitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=255)),
                ('notitie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='oefeningen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afbeelding', models.ImageField(blank=True, upload_to='jouwteam/images')),
                ('titel', models.CharField(max_length=255)),
                ('beschrijving', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='speler',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('spelernummer', models.CharField(max_length=5)),
                ('voornaam', models.CharField(max_length=255)),
                ('achternaam', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='spelerlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailadres', models.CharField(max_length=255)),
                ('teamcode', models.CharField(default='False', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='tactieken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='trainer',
            fields=[
                ('gebruikersnaam', models.CharField(default='False', max_length=200, primary_key=True, serialize=False)),
                ('emailadres', models.CharField(max_length=255)),
                ('wachtwoord', models.CharField(max_length=32)),
                ('teamcode', models.UUIDField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='wedstrijduitslag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thuis', models.CharField(max_length=255)),
                ('uit', models.CharField(max_length=255)),
                ('stand', models.CharField(max_length=25)),
                ('verslag', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='inloggen',
        ),
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.CreateModel(
            name='aanwezigheid',
            fields=[
                ('speler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccer.speler')),
                ('datum', models.DateTimeField(verbose_name='')),
                ('aanwezig', models.BooleanField()),
            ],
            bases=('soccer.speler',),
        ),
    ]
